### ISSUE TITLE
ValueError: No valid path is found for training., Colab error

### ISSUE THREAD

**Issue by Pavankunchala** [enhuiz/vall-e#20] opened 2023-01-19 20:31 UTC
I am getting this error in collab 

I have created a new folder under data called custom 
![image](https://user-images.githubusercontent.com/39479635/213553051-189c9bb3-cbe9-4622-99e6-037a9afbacae.png)

After that I have created new YML files under a new folder 
![image](https://user-images.githubusercontent.com/39479635/213553317-39079e45-a26c-458a-b4d5-c41dcdb9c645.png)

Here is the ar.yml 
![image](https://user-images.githubusercontent.com/39479635/213553401-6701f4e7-616f-4052-a860-fd68fd6f20c4.png)

I am getting this error now any suggestions

**Comment by finardi** [comment] 2023-01-19 20:58
Which error? Can you please copy the error here.

**Comment by psteller** [comment] 2023-01-19 21:02
I am seeing the same error.


python -m vall_e.train yaml=config/custom/nar.yml 
1it [00:00, 5236.33it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/peter/vall-e/vall-e/vall_e/train.py", line 128, in <module>
    main()
  File "/home/peter/vall-e/vall-e/vall_e/train.py", line 33, in main
    train_dl, subtrain_dl, val_dl = create_train_val_dataloader()
  File "/home/peter/vall-e/vall-e/vall_e/data.py", line 266, in create_train_val_dataloader
    train_dataset, val_dataset = create_datasets()
  File "/home/peter/vall-e/vall-e/vall_e/data.py", line 247, in create_datasets
    train_dataset = VALLEDatset(
  File "/home/peter/vall-e/vall-e/vall_e/data.py", line 105, in __init__
    raise ValueError("No valid path is found for training.")
ValueError: No valid path is found for training.

**Comment by finardi** [comment] 2023-01-19 21:11
I bet that your data exceed the number of max phonemas (pre setted to 50). Look at line 105 of data.py and print the local variable of max_phonema before this line and configure a new max that the _validate function do not return not an empty list.

**Comment by psteller** [comment] 2023-01-19 23:04
I reduced the length of my wav file and confirmed that the _validate function finds 20 phones.

I am still getting the same error, though, regardless of what I set the max_phones value to in my config file.

The self.paths_by_spkr_name variable contains:
'test': [PosixPath('data/test/test.qnt.pt')]

The problem seems to be with assigning a value to self.paths just prior to the error in data.py:
p for p in self.paths if len(self.paths_by_spkr_name[cfg.get_spkr(p)]) > 1

Training is true, but len(self.paths) is zero, triggering the "No valid path is found" error.

**Comment by finardi** [comment] 2023-01-19 23:26
Humm, I see

Maybe you need to duplicate the files, like the original test folder has or put more than one file in your custon dir

**Comment by psteller** [comment] 2023-01-19 23:43
Confirmed. It seems to need more than one pair of qnt and phn files. Creating a second set resolved the problem. Thanks!

**Comment by enhuiz** [comment] 2023-01-21 08:03
Closing this, you may also refer to: https://github.com/enhuiz/vall-e/issues/6

**Closed as completed by enhuiz** 2023-01-21 08:03 UTC
